duckduckgo/zeroclickinfo-fathead

- lib/DDG/Fathead/MDNJS.pm
- share/mdnjs/fetch.py
- share/mdnjs/fetch.sh
- share/mdnjs/parse.py
- share/mdnjs/parse.sh
> update MDN fathead to new output file format

- lib/DDG/Fathead/MadeHow.pm
- share/fathead/made_how/README.txt
- share/fathead/made_how/fetch.sh
- share/fathead/made_how/parse.rb
- share/fathead/made_how/parse.sh
**What does your Instant Answer do?**
References How Products Are Made (http://www.madehow.com) for information on how different products are manufactured.  This was initial proposed [here](https://duck.co/ideas/idea/4750/how-things-are-made).
**What problem does your Instant Answer solve (Why is it better than organic links)?**
It gives you quick info immediately with the option to find out more.
**What is the data source for your Instant Answer? (Provide a link if possible)**
How Products Are Made (http://www.madehow.com)
**Why did you choose this data source?**
It was listed in the initial proposal.  It's a really cool site too.
**Are there any other alternative (better) data sources?**
Not that I know of.
**What are some example queries that trigger this Instant Answer?**
Anything …
> How Products Are Made fathead

- lib/DDG/Fathead/Abbreviations.pm
- share/fathead/abbreviations_com/README.txt
- share/fathead/abbreviations_com/fetch.sh
- share/fathead/abbreviations_com/meta.txt
- share/fathead/abbreviations_com/parse.py
- share/fathead/abbreviations_com/parse.sh
Fathead Pull Request Template
Using this template will help us better understand your Instant Answer and assist you when necessary. Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.
What does your Instant Answer do?
- It provides instant answers to acronyms and abbreviations related queries.
What problem does your Instant Answer solve (Why is it better than organic links)?
- It save the user making redundant clicks by giving the most popular definition for a term.
What is the data source for your Instant Answer? (Provide a link if possible)
- http://www.abbreviations.com
Why did you choose this data source?
- We are the operators of Abbreviations.com and been approached by the Business Development Team at DuckDuckGo
Are …
> Abbreviations.com IA Fathead Plugin

- dist.ini
Reverts duckduckgo/zeroclickinfo-fathead#149
> Revert "Make dist.ini consistent with other repos"

- pull_request_template_fathead.md
fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1625
* Added windows 10 as a new platform.
* Added Linux as a new platform.
> Added Windows 10 and Linux as platforms for fathead

- dist.ini
Use new dzil plugin to update tag message on release
> Use Git::Tag::IAChangelog

- LICENSE
Updated license to contain full text.
> License: full text

- lib/fathead/nodejs_ref/fetch.sh
Quick fix for #218 , @moollaza 
---
https://duck.co/ia/view/node_js
> NodeJSRef: Fix fetch URL

- lib/fathead/mdnjs/fetch.py
- lib/fathead/mdnjs/parse.py
- lib/fathead/mdnjs/tohtml.py
Improve Python code style, now we follow the PEP-8 coding conventions.
https://duck.co/ia/view/mdnjs
/cc @ericedens
> Adopt PEP-8 coding standard for Python

- lib/fathead/python/parse.py
Two new things:
1. general overview for each module
https://beta.duckduckgo.com/?q=python+asyncio&t=ha&ia=about
2. parse all methods for each class
https://beta.duckduckgo.com/?q=python+unittest+testloader.getTestCaseNames&t=ha&ia=about
I didn't try to create a bunch of redirects. We can handle that in a separate PR. 
------
IA Page:  http://duck.co/ia/view/python 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaulrobe
> Python: parse all class methods

- lib/fathead/python/redirect.py
Work in progress. Addresses issue #265.
---
> Additional redirects to Python fathead

- lib/fathead/python/redirect.py
Continuing from #270 
Generating all permutations of `(package, class, method)`.
cc: @jrasanen 
----
> python: add permutations

- lib/fathead/idris_doc/fetch.sh
- lib/fathead/idris_doc/parse.pl
- lib/fathead/idris_doc/parse.sh
- lib/fathead/idris_doc/trigger_words.txt
FatHead for Idris documentation.
---
IA Page: https://duck.co/ia/view/idris_doc
Maintainer: @GuiltyDolphin
> New IdrisDoc FatHead

- lib/fathead/mdn_css/parse.pl
Move the paragraph wrapping into `build_abstract()`
/cc @hchienjo 
> Wrap $initial_value with paragraph tags in build_abstract sub

- lib/fathead/mdn_css/parse.pl
Unfortunately I misunderstood how External Links work.
Removing this code for now, if Fatheads change to meet my expectations we can bring this back.
Will be added to #311
/cc @hchienjo 
---
> MDN CSS: Remove external links (for now..)

- lib/fathead/mdn_css/parse.pl
Ongoing PR for multiple updates to MDN CSS Fathead
- #310 - Wrap `$initial_value` with `<p>` inside `build_abstract` sub
- #311 - Remove `external_links`
/cc @hchienjo 
----
> Ongoing Updates to MDN CSS 

- lib/fathead/python/parse.py
- lib/fathead/python/redirect.py
> Displays builtin functions for python fathead.

- lib/fathead/mdn_css/parse.sh
> MDN CSS: Ensure traditional sort order

- lib/fathead/mdn_css/fetch.pl
- Remove repetitive fetching of urls with same path but different fragments.
- Iterate only once when dividing urls with fragments and those without fragments while writing to fragments.txt file.
- Also avoid putting urls with same path but different fragments in the fetch pipeline since we only need to fetch one url without the fragment and it will contain data for all the fragments.
cc @moollaza 
> MDN CSS: Improve sorting, fetching of urls.

- README.md
1. Updated README to reflect the Programming Mission: https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53
- We are focused on validating the tools/processes used to create Instant Answers on DuckDuckGo by working directly with contributors to a single search topic: Programming-related searches. We're starting with CSS, JS, Perl, Python, and Swift but plan to expand into other programming languages/frameworks (and other topics) as the new community grows. 
2. Introduces the focus and policy on programming-related Instant Answers: 
- We are only reviewing/accepting Pull Requests/Issues within the Programming Mission.
> Update README for prog mission alert

- CONTRIBUTING.md
Update contributing.md for Programming Mission callouts
@alohaas
> more updates for programming focus

- lib/fathead/mdnjs/fetch.sh
- lib/fathead/mdnjs/output.txt
- lib/fathead/mdnjs/parse.py
Fixing #280 [WIP]
https://github.com/duckduckgo/zeroclickinfo-fathead/issues/280#issuecomment-241023585
----------------------------------
IA Page: https://duck.co/ia/view/mdnjs
Forum topic: [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155)
This pull request is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!
> Improving MDN Javascript Fathead

- lib/fathead/apple_docs_ios/parse.py
> AppleDocsIOS: Remove MacOS reference links

- lib/fathead/apple_docs_macos/parse.py
> AppleDocsMacOS: Remove unnecessary iOS referrences

- lib/fathead/python/parse.py
- lib/fathead/python/parse.sh
- lib/fathead/python/redirect.py
> Python: Fix #297 -- Added disambiguations for deleted keys.

- lib/fathead/perl_doc/Parsers/parse.pl
https://docs.duckduckhack.com/resources/fathead-overview.html
Thanks!
> PerlDoc: Change EOL char to \n as specified in docs

- lib/fathead/mdn_css/fetch.pl
Attempted to add fetching of URLs for the -webkit and -moz extensions in fetch.pl. For #293 
Please review :)
@moollaza @hchienjo 
IA Page: https://duck.co/ia/view/mdn_css
Maintainer: @hchienjo
> MDN CSS: Add support for -webkit and -moz extensions

- lib/fathead/python/redirect.py
https://duck.co/ia/view/python
fixes #360
> Fix #360: Python: Ignores 'The Python Tutorial' entry.

- lib/fathead/python/parse.py
> Fix #361: Python: Fixes new line issue in method abstracts.

- lib/fathead/jquery/output.txt
- lib/fathead/jquery/parse.js
Closes #410.
---
http://duck.co/ia/view/jquery
> jQuery: Use new Fathead template elements

- lib/fathead/java/parse_utils.py
Explicitly specify html parser to avoid warnings.
Fixes #442 
cc @moollaza 
IA Page: http://duck.co/ia/view/java
> Java: Proposed fix for #422

- lib/fathead/apple_docs_watchos/README.txt
- lib/fathead/apple_docs_watchos/fetch.sh
- lib/fathead/apple_docs_watchos/parse.py
- lib/fathead/apple_docs_watchos/parse.sh
A new Fathead for the Apple watchOS, similar to our iOS, macOS and tvOS Fatheads
----
- IA Page: https://duck.co/ia/view/apple_docs_watchos
- [Forum Link](https://forum.duckduckhack.com/t/create-a-fathead-that-shows-watchos-apis/935)
> New Instant Answer: Apple Docs watchOS Fathead

- lib/fathead/perl_doc/Parsers/parse.pl
Fixes #414 
---
Maintainer: @GuiltyDolphin
> PerlDoc: Update to use new FatHead templates

- lib/fathead/django_built_ins/parse.py
IA Page: https://duck.co/ia/view/django_built_ins
> Fix #408: Django Built-Ins - Switched to new fathead template. 

- CONTRIBUTING.md
- README.md
* Removed some duplication in the two files.
* `CONTRIBUTING.md`: Pointed specifically to the "How to contribute" page. 
* `CONTRIBUTING.md`: Changed IA examples to programming related.
> Simplified README and CONTRIBUTING

- .github/PULL_REQUEST_TEMPLATE.md
Simplify the html comments in the PR template so it's easier to read and modify
> PR Template: Simplify HTML comments

- lib/fathead/python/parse.py
Switched to new fathead template. 
Fixes #416 
@moollaza @gaulrobe @pjhampton 
---
Forum Topic: https://forum.duckduckhack.com/t/python-docs-fathead/176
> Fix #416: Python - Switched to new fathead template. 

- lib/fathead/diveintopython/parse.py
Fixes #424 
---
IA Page: https://duck.co/ia/view/diveintopython
> Fix #424: Dive Into Python - Switched to new fathead template.

- lib/fathead/perl6doc/parse.pl
Making use of new fathead template elements.
Fixes #413 
@moollaza @GuiltyDolphin 
---
Instant Answer Page: https://duck.co/ia/view/perl6doc
> Perl6doc: Switch to use new Fathead Template Elements

- lib/fathead/cppreference_doc/README.md
Updates the README file to indicate where the parsing script is located.
Related to the discussion in #407 and #539 
@moollaza @sahildua2305 
---
Instant Answer Page: https://duck.co/ia/view/cppreference_doc
Maintainer: @ManrajGrover
> CPPReference Fathead: Update README file

- lib/utils/extract_articles.pl
This script takes one argument, the IA id, (e.g. `perl utils/extract_articles.pl angularjs`) and:
- reads its output.txt file line by line
- stores the article titles in an array
- writes the titles to a new "articles.txt" file in the IA dir
@russellholt @moollaza
> Utils - Add a simple script to pull out article titles for any Fathead in a new file

- lib/fathead/caniuse/articles.txt
Add the articles.txt file containing just the article titles from the output.txt file to facilitate adding redirects.
Prerequisite for issue #172 
@russellholt @tagawa 
---
Instant Answer Page: https://duck.co/ia/view/caniuse
> Can I Use - add articles.txt file

- .github/PULL_REQUEST_TEMPLATE.md
Adds a GitHub checklist to the Fathead PR template, to be completed by the PR reviewer. Also contains a link to the full PR review guidelines in the DDH Documentation.
@MariagraziaAlastra @tagawa
> PR Template: Add PR Review checklist and link to full PR review guidelines

- lib/fathead/reactjs/articles.txt
Add list of articles to ReactJS
Needed for #597 
---
Instant Answer Page: https://duck.co/ia/view/reactjs
> ReactJS - add articles.txt

- lib/fathead/php/parse.js
Fixed #568 
@moollaza
---
Instant Answer Page: https://duck.co/ia/view/php
> PHP: Fix parser throwing exception when using fs module

- lib/fathead/jquery/articles.txt
- lib/fathead/jquery/output.txt
Add the list of articles in articles.txt, and also the latest output.txt.
We identified some tasks involving the creation of new redirects, see the [jQuery forum topic](https://forum.duckduckhack.com/t/improve-jquery-fathead/180/11). 
They will soon have GitHub issues
---
Instant Answer Page: https://duck.co/ia/view/jquery
> jQuery - add articles.txt as well as the updated output file

- lib/fathead/php/parse.js
Fixes #614 
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/php
> PHP: Fix output tab count on php fathead

- lib/fathead/reactjs/redirects.py
- lib/fathead/reactjs/redirects.txt
Add list of redirects to ReactJS
Fixes #597 
---
Instant Answer Page: https://duck.co/ia/view/reactjs
> React API Docs: Broaden search results by adding more aliases (#597)

- lib/fathead/jquery/redirects.txt
This PR fixes issue #612. Specifically, it adds the aliases listed in the issue for `jQuery :checked Selector` to the `redirects.txt` file.
https://duck.co/ia/view/jquery
@bfmags 
- Source Info (used as Subtitle for each Article -- usually matches the IA …
> jQuery: Add article aliases (redirects) -- :checked Selector

- lib/fathead/pika/redirects.txt
Fixes : #655 
@MariagraziaAlastra 
- Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)
- Tester should report …
> Pika: added redirects.txt

- lib/fathead/mdnjs/README.txt
- lib/fathead/mdnjs/parse.py
show the first example in the article
fixes #530
@MariagraziaAlastra 
- Source ID (ping @moollaza to assign one, once Fathead is ready for …
> MDN JS: show the first example in the article (#530)

- lib/fathead/mdn_css/redirects.txt
Adds aliases for composite words.
Fixes issue #639.
@MariagraziaAlastra 
@hchienjo 
- Source ID (ping @moollaza to assign one, once Fathead …
> MDN CSS: Add aliases -- composite words. (#639)

- lib/fathead/php/README.txt
- lib/fathead/php/package.json
- lib/fathead/php/parse.js
php: udpated the coverage to cover more functions
* covered functions from classes (~6000 are remaining)
* double documentation with classname and without classname both
Improvement: #616
@VitorVRS @gautamkrishnar
* Tested by @gautamkrishnar : Not triggering. Found duplicates.
- Source Domain (must contain …
> adding more coverage to the php functions

- lib/fathead/node_js/redirector.sh
- lib/fathead/node_js/redirects.txt
NodeJS: Fixing #511 
A work in progress, adding redirects.
Fixing #511 
@pjhampton 
- …
> Nodejs: Add Redirects for improved coverage

- lib/fathead/angularjs/output.txt
- lib/fathead/angularjs/trigger_words.txt
Angularjs: Fixes #755 
This PR adds trigger_words.txt file for this IA
Along with angular js angular javascript trigger is also added to increase the coverage
"Fixes #755"
@pjhampton @rafaelpadovezi 
- …
> Angularjs: trigger_words.txt added

- lib/fathead/sqlalchemy/parse.py
Fixed minor indentation issue in sqlalchemy parser.
No issues reported.
@moollaza 
- …
> Sqlalchemy: Fixed minor indentation issue.

- lib/fathead/node_js/redirector.sh
- lib/fathead/node_js/redirects.txt
- lib/fathead/node_js/trigger_words.txt
adding trigger_words.txt
Fixes #511
@pjhampton
- Source ID (ping @moollaza to assign …
> Nodejs: Add trigger words for improved coverage

- lib/fathead/scipy/trigger_words.txt
Updated the scipy IA triggers based on the unanswered query data. 
- Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)
**Code**
- …
> Scipy Improvement: Added bi-gram trigger word

- lib/fathead/sass/trigger_words.txt
Adding these triggers based on the unanswered query data. 
- Source ID (ping @moollaza …
> Sass Suggestion: Added trigger words to Sass Fathead.

- lib/fathead/react_native/trigger_words.txt
The new React-Native Fathead is badly under triggering. I suspect this is because there are no trigger words. I have added them here quickly instead of creating an issue and waiting for someone to do it.
@moollaza 
@Hestben 
- Source Domain (must contain http:// or https:// -- can be …
> Added React Native trigger words.

- lib/fathead/itext7/trigger_words.txt
Added the trigger iText7 to the itext 7 fathead.
Fixes: #769 
@moollaza 
@pjhampton 
- …
> iText7: New Trigger

- lib/fathead/apple_docs_ios/parse.py
Removes redirects to stop overtriggering.
- Source ID (ping @moollaza to assign one, …
> Apple Docs (iOS): Nuke iOS redirects.

- lib/fathead/apple_discussions/parse.py
- lib/fathead/apple_discussions/parse.sh
Fixes parsing issues discussed with @moollaza 
- Source ID (ping @moollaza to assign …
> Apple Discussions: Fix parser.
