duckduckgo/zeroclickinfo-fathead

share/fathead/airports/README.txt, share/fathead/airports/parse.py
The first commit fixes PEP8 errors.
The second commit adapts the fathead to the current table layout.
At this point, the fathead is working again, and the followup commits
in this branch are just improvements over the generated data.
The only other crucial change is commit
3892bdfa34e3d54ef8a182e9a9233451738c80e9, which updates airport links
to point to the airport's Wikipage (instead of the list of airports).
=> Airports fix

lib/DDG/Fathead/Abbreviations.pm, lib/DDG/Fathead/MadeHow.pm
* Updated example primary queries for Abbreviations and MadeHow.
Signed-off-by: mr.Shu <mr@shu.io>
----------------------
The examples that were in use for these fatheads previously did not trigger on DuckDuckGo.com. Those in this commit should trigger.
=> update: Updated primary example queries

lib/DDG/Fathead/CountryLanguages.pm, share/fathead/country_languages/README.txt, share/fathead/country_languages/fetch.sh, share/fathead/country_languages/parse.js, share/fathead/country_languages/parse.sh
This is an attempt to add the Fathead as discussed here: https://duck.co/ideas/idea/515/languages-of-a-country. I have seen that someone else was also working on this Fathead (https://github.com/duckduckgo/zeroclickinfo-fathead/pull/54) but never finished it, so I decided to give it a try.
I'm not sure if the generated output.txt contains all the necessary information, so I have included a snippet:
```
1.Full article title	2.Type of article	3.For redirects only	4.Ignore.	5.Categories. 	6.Ignore.	7.Related topics. 	8.Ignore.	9.External links.	10.For disambiguation pages only. 	11.Image. 	12.Abstract. 	13.URL. 
Uzbekistan	A										Uzbek (official) 74.3%, Russian 14.2%, Tajik 4.4%, other 7.1%	https://www.cia.gov/library/publications/the-world-factbook/geos/uz.html
Vanuatu	A										local …
```
=> New Fathead, see: https://duck.co/ideas/idea/515/languages-of-a-country

share/fathead/plural/extract_plurals.pl
In response to issue #145, this fixes the way the 'plural' fathead parses Wiktionary noun inflection lists. In particular it handles cases where a qualifier such as 'archaic' or 'uncommon' is given, and is a little smarter about not letting unwanted or malformed text find its way into the IA. After applying these changes the result for 'plural moose' should look like 'The plural of moose is meese (uncommon, humorous); moose; or mooses.'
https://duck.co/ia/view/plural/
=> Improve extraction of plural forms from Wiktionary

share/fathead/plural/extract_plurals.pl
Fixes a bug introduced into the Plurals IA in #146. Restores handling of the situation where no plural form is specified so '-s' is assumed.
----
https://duck.co/ia/view/plural
=> Plurals: restore parsing of '-s' plurals

dist.ini
* Remove unnecessary plugins
* Prevent most share assets from going in release
* Scan fathead namespace only
=> Make dist.ini consistent with other repos

dist.ini, lib/DDG/Fathead/Meta.pm
Metadata is no longer needed in the repos.
=> Remove metadata

share/fathead/cppreference_doc/README.md, share/fathead/cppreference_doc/data.url, share/fathead/cppreference_doc/fetch.sh
This implements a suggestion that Jason has made in a private email that we add a layer of indirection in tracking the release tarballs: cppreference.com now has a separate webpage that only contains the link to the latest release tarball that DuckDuckGo should use.
https://duck.co/ia/view/cppreference_doc
=> Cppreference-doc: Track a link to the release tarball, not the tarball itself

dist.ini
Should be mostly similar to goodies/spices.  Commented out the AutoModuleShareDirs since we don't have a share dir at the moment.
After this we should release using `V` to force the version.
=> Update dist.ini to match other repos

lib/fathead/py_pi/parse.py
Updating the [pypi fathead](https://duck.co/ia/view/py_pi)
- removed number of downloads and latest release. We don't update the data often enough to ensure this doesn't go stale
- added pip install command for people who like to copy/paste
- added a link to the official site if one exists
=> Update pypi fathead

lib/fathead/mdn_css/fetch.pl, lib/fathead/mdn_css/parse.pl
Implement parsing of the fragments after the following paths:
for [`/font-variant/`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variant) and [`src`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src#local()) the pages generate 404 codes so I have left a [note](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/292/commits/5fc9ac6e256c8ad2e5d260890d969e0e259c22f1) so that they will be implemented when the pages are fixed.
Other tasks:
This is still work in progress.
=> Enhancing MDN CSS Fathead

lib/fathead/mdn_css/parse.pl
1.  Added correct parsing of initial values embedded in `<ul>`.
2. Remove extra spaces from units of angle (like deg) and units of frequency.
I have tested the changes on codio and they look fine to me.
@moollaza please review.
=> MDN CSS: Cleanup in initial value and code fragments parsing.

lib/fathead/mdn_css/parse.sh
This force the output.txt file to be alphabetically sorted via unix `sort`.
This way, it will be easier to visually detect any duplicates and ensures that when a new output.txt is created, only new/modified content will show in the diff, as the ordering is currently random.
/cc @hchienjo 
=> MDN CSS: sort output.txt

lib/fathead/caniuse/README.txt, lib/fathead/caniuse/parse.py
Fixes #245. I've added the 'notes' from the input data to the 'abstract' field as well as adding the links from the input data to the 'related' field in the IA. Also added support for the "TP" release version used by Safari to indicate "Technology Preview" -- we treat this as the latest version of the browser. 
This will requires some testing to make sure the links show up right as they might not be at the moment. It looks like to fix the triggering issue we should add some internal triggering words (specifically "compatibility") to fix everything discussed in issue 245. 
---
https://duck.co/ia/view/caniuse
Maintainer: @csytan
=> CanIUse: Adding notes to abstract as well as related links

lib/fathead/mdn_css/parse.pl
Put the cleaned title in the redirect field so that it points to the right article.
Please not that I have not generated the output.txt after making this change.
cc @moollaza 
=> MDN CSS: Put cleaned title in redirect field.

lib/fathead/perl_doc/Parsers/parse.pl
Fixes #340.
* Core modules are now supported.
* Content is brief summary (from name) + synopsis.
* 'See also' is used for the related topics.
---
Maintainer: @GuiltyDolphin
=> PerlDoc: Add support for modules

lib/fathead/perl_doc/Parsers/parse.pl
This is why entries for for, foreach and so on went missing.
IA Page : https://duck.co/ia/view/perl_doc
=> PerlDoc : Restore index-language parsing.

lib/fathead/apple_docs_ios/README.md, lib/fathead/apple_docs_ios/parse.py, lib/fathead/apple_docs_ios/parse.sh
Changes:
- Redirects so that things like "nsstring length", "length nsstring", and "nsstring.length" all work Fixes #282 
- Splits it into two IAs because the triggers are different for each, e.g., "ios nsstring" should show apple_docs_ios and "osx nsstring" should show apple_docs_macos. Fixes #315 
- SQLite query is now updated to work with XCode 7.3.1 docsets
- Fixes https://github.com/duckduckgo/zeroclickinfo-fathead/issues/320
https://duck.co/ia/view/apple_docs_ios
=> Add Apple Docs for iOS

lib/fathead/apple_docs_macos/README.md, lib/fathead/apple_docs_macos/parse.py, lib/fathead/apple_docs_macos/parse.sh
Changes:
- Redirects so that things like "nsstring length", "length nsstring", and "nsstring.length" all work Fixes #282 
- Splits it into two IAs because the triggers are different for each, e.g., "ios nsstring" should show apple_docs_ios and "osx nsstring" should show apple_docs_macos. Fixes #315 
- SQLite query is now updated to work with XCode 7.3.1 docsets
- Fixes #307 
https://duck.co/ia/view/apple_docs_macos
=> Add Apple Docs for macOS

lib/fathead/mdnjs/output.txt, lib/fathead/mdnjs/parse.py
IA Page: http://duck.co/ia/view/mdnjs
=> mdnjs: issue #372 -- redirects without punctuation for error articles

lib/fathead/perl_doc/Parsers/parse.pl
Adds categories to perl_doc, fixes #321.
- `Perl Error Variables` (category) may clash with `Error Variables` (FAQ article).
cc @jbarrett 
---
Maintainer: @GuiltyDolphin
=> PerlDoc: Add categories

lib/fathead/mdn_css/parse.pl
Current Changes
===============
1. Parse description from the body of html to avoid truncated descriptions.
2. Improve efficiency in title parsing.
3. Avoid spurious warnings about use of uninitialized values.
WIP
=======
Work on fixing a duplication of `color` in output.txt file
cc @moollaza 
IA Page: https://duck.co/ia/view/mdn_css
=> MDN CSS: Improve description and title parsing.

lib/fathead/nodejs_ref/parse.js
- Removed "methods" key, which was removed from documentation. 
It's childrens (setTimeout, clearTimeout, setInterval, dns.lookupService) were moved to other sections (globals and module)
---
Fixes #436 
http://duck.co/ia/view/node_js
=> Fix #436: NodeJS: Updatde Parser to latest API

lib/fathead/py_pi/parse.py
Fixes  #423
Use the fathead template for formatting the output. Details in https://docs.duckduckhack.com/resources/fathead-overview.html#formatting-the-abstract.
Old output:
`Create CovJSON files from common scientific data formats<br>Development status:
Beta<br><pre><code>pip install pycovjson</code></pre>`
New output:
`<section class="prog__container"><p>Create CovJSON files from common scientific
data formats</p><p>Development status: Beta</p><pre><code>pip install pycovjson</code></pre></section>`
Issue:https://github.com/duckduckgo/zeroclickinfo-fathead/issues/423
IA Page: http://duck.co/ia/view/py_pi
Maintainer: @ezgraphs
CC: @pjhampton
=> Fix  #423: PyPi: Switch to use new Fathead Template Elements

lib/fathead/java/parse_utils.py, lib/fathead/java/test_parse_utils.py
Fixes #201: Java: Doesn't trigger on some terms
This fix contains 2 changes.  
1. parse_utils.py is updated to exclude type parameters in class names.  As an example, `'ArrayList<E>'` is now included as 'ArrayList' in the output file.  This ensures users searching for 'ArrayList' will get a result back from this java fathead IA.  
2. test_parse_utils.py is updated with relevant test cases for this change.
IA Page: http://duck.co/ia/view/java
Maintainer: @boyter
Cc: @marti1125
=> Java: Fixes #201 - Updated parser to exclude type parameters in class names

lib/fathead/py_pi/requirements.txt
As requested by @moollaza in https://github.com/duckduckgo/zeroclickinfo-fathead/pull/440, add requirements.txt to simplify the setup of the environment needed to execute this fathead.
In the Readme.md file, it is incorrecly stated that you should install the python-dev packet with 'sudo apt-get install python-dev'. But on codio, apt-get cannot be used, so you need to use 'parts install' instead. I don't remember if I had to install the python-dev package manually, or if it was already installed. At least, I needed to install 'pip' using 'parts'.
Is that something I should update in this PR as well?
---
IA Page: https://duck.co/ia/view/py_pi
Forum Topic:
=> PyPi: Fix #423 Switch to use new Fathead Template Elements - follow up

lib/fathead/perl_doc/Parsers/parse.pl
Removes leading `<p>` tags after function syntax.
@moollaza 
---
Forum Topic:
=> PerlDoc: Remove leading (empty) <p> tags from functions

.github/NEW_IA_TEMPLATE.md
Adds a template for New Instant Answers. It cannot be used automatically by GitHub, but we may replace the standard issue template with this.
For now I'm putting this here to flesh out the details and have a copy somewhere public.
@MariagraziaAlastra @tagawa @russellholt
=> Create NEW_IA_TEMPLATE.md, based off PJHampton's template

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
- Make Issue Template HTML comments easier to read
- Add in "Get Started" and "Resources" to be included when Language Leaders are creating issues (meaning they are approved to be worked on)
- Remove "Type of Issue" selection box. Takes up lots of space, and information can be conveyed by title + labels
@tagawa @MariagraziaAlastra
=> Include Get Started & Resources in Issue Template; Minor changes to PR Template

lib/fathead/py_pi/parse.py
As pointed out by Jason in https://forum.duckduckhack.com/t/py-pi-fathead-ux-improvements/194/7?u=hestben that links to package home page should be showed. I found that there is actually already links to home pages shown, but it only showed links starting with 'www.'. This fix also allows links starting with 'http://' and 'https://'.
Before this search correctly showed a link to the home page: https://duckduckgo.com/?q=python+numpy
While this search did not: https://duckduckgo.com/?q=python+pandas&ia=about
Now, both should work.
Maintainer: @ezgraphs @pjhampton 
---
Instant Answer Page: https://duck.co/ia/view/py_pi
=> Py_pi:Fix detection of package home page links

lib/fathead/java/parse_utils.py
This change is to switch the java fathead IA to use the new fathead template elements.
It also increases the abstract length (from 100 to 300) to display more details to the user from oracle docs.
Fixes #409: Java: Switch to use new Fathead Template Elements 
@marti1125 @moollaza @boyter 
IA Page: http://duck.co/ia/view/java 
Forum Topic:
=> Java: Fixes #409: Switch to use new Fathead Template Elements and Increase Length of Abstract

lib/fathead/httplib2/README.txt, lib/fathead/httplib2/fetch.sh, lib/fathead/httplib2/parse.py, lib/fathead/httplib2/parse.sh, lib/fathead/httplib2/requirements.txt
To help me for this issue, I've watched how it was done for the [beautifulsoup fathead](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/beautifulsoup/parse.py).
In particular, I didn't add any categories because it didn't seem appropriate.
For the abstract, there are two other things I'm not sure about:
- There were no examples of codes for the lib functions, so I've put the complete signature in the code part and the first paragraph of the description as the abstract.
- I've removed the HTML tags of the description and took only the first paragraph, but it might be problematic, for example [here](https://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http.force_exception_to_status_code) and …
=> Add httplib2 Fathead (closes #452)

lib/fathead/py_pi/parse.py, lib/fathead/py_pi/requirements.txt
Limit pypi to only popular packages.
Fixes #533 
@moollaza @jdorweiler 
---
Instant Answer Page: https://duck.co/ia/view/py_pi
=> Fix #533: Python -  Limit pypi to only popular packages.

lib/fathead/perl6doc/fetch.sh
- Ensure the fetch URL for perl6.org uses `https`.
@sahildua2305  @GuiltyDolphin 
---
Instant Answer Page: https://duck.co/ia/view/perl6doc
=> Perl6Doc: Switch fetch URL to https

t/lib/TestUtils.pm
- Fixed the check for the `cover/` dir.
- Ensure `$titles` from output.txt are lowercased when compare against lowercased `$cover_titles`
=> Fix Fathead Test

t/lib/TestUtils.pm
- improve regex to catch `/\n\r\t/` instead of `/\\n, \\r, \\t/`
=> Fathead Tests: Update regex to properly catch \n \r \t and \[0-9x]

README.md
Change "Learn more"  link to DDH.com instead of Forum
/cc @tagawa
=> Update link to DuckDuckHack.com

lib/fathead/python/redirect.py
Issue #526 
I have created this PR to discuss what we should do, and comment on the code.
@souravbadami I see you have touched the code last. Maybe you would like to take this issue, if you have time. I don't want us to do double work =).
From my initial investigation, I have found that the view that is shown in the search result in #526 example comes from a Disambiguation entry created in redirect.py.
Does anybody have an example where a Disambiguation is the correct thing to show? If we strip out some stuff, we wouldn't want to destroy cases where disambiguations should be used.
I have found more cases where I think we would like to change the view, as @jdorweiler suggested in the #526:
https://duckduckgo.com/?q=python+shlex&t=ffsb&ia=meanings&iai=%2F35%2Fshlex.quote …
=> Python: Fix #526 add coverage for more classes

lib/fathead/python/parse.py, lib/fathead/python/parse.sh, lib/fathead/python/redirect.py
I was trying to generate the output file for Python in my instance, using python 3.5.2 as recommended in the README, and I got an error both in parse.py and redirect.py, on the [lines trying to force UTF-8 encoding](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/python/redirect.py#L5-L8).
I replaced it with a line in parse.sh, and now it works smoothly.
@pjhampton 
---
Instant Answer Page: https://duck.co/ia/view/python
=> Python - Remove deprecated workaround forcing UTF-8 encoding

t/lib/TestUtils.pm, t/validate_fathead.t
- Fixed several small bugs in tests
- Skip disambiguation checks when none exist
- Update output to list our problematic titles/duplicates/disambigs, etc
- Allow `validate_fatheads.t` to take single Fathead from ENV or default to checking all output.txt in the repo
#567 - Adding Travis support to Repo
@jbarrett
=> Fathead Tests: Update to loop over all output.txt

lib/fathead/py_pi/parse.py
Increases the number of pypi packages from [pypi-rankings](http://pypi-ranking.info/) from 10,000 to 15,000
Fixes #598 
@moollaza @jdorweiler @tagawa 
---
Instant Answer Page: https://duck.co/ia/view/py_pi
=> Fixes #598: Increase number of pypi packages from pypi-rankings to 15,000

lib/fathead/mdn_css/redirect.txt
Fixes #637. MDN CSS entries like "background-color" weren't being triggered by searches like "color background". Added redirects.txt aliases to specify these cases explicitly.
Instant Answer Page: https://duck.co/ia/view/mdn_css
=> MDN CSS: Add aliases for background-*

lib/fathead/python/parse.py
Fixes #605 
With this more restrictive parsing, results such as "21.1. audioop — Manipulate raw audio data" will not appear in output.txt.
This also solves an issue with python2 "print" getting a result from a tutorial page, rather than the library reference. In the old parse, you can look in output_py2.txt, and see, that there are 3 entries for "print", and the one we want to display, appears last, and thus, an erroneous one is used, because it appears earlier in the output_py2.txt.
Maintainer: @gaulrobe 
- Description, …
=> Python: Fix #605 More restrictive when parsing.

lib/fathead/django/fetch.sh, lib/fathead/django/output_statistics.awk, lib/fathead/django/parse.py, lib/fathead/django/parse.sh, lib/fathead/django/redirect.py
* Sort output uniquely.
The original output had 1101 lines. Now the unique output shows that
only 359 entries were actually unique.
* Download all sources, not specific pages.
* Parsing module names, functions, methods and attributes.
* Add redirect.py and sort properly and uniquely.
* Add output_statistics.awk
* Add output.txt.
This is a complete rework of the fathead, and adds a lot of articles and a huge amount of redirects.
One con is that the [django allowed_hosts](https://duckduckgo.com/?q=Django+allowed_hosts&ia=about) query and other queries for settings will not work. I could look into that, if it is necessary.
Fixes #766 
@pjhampton 
- …
=> Django: Rework fathead to handle sub modules

.gitignore, lib/fathead/cppreference_doc/README.md, lib/fathead/cppreference_doc/cppreference-doc/build_link_map.py, lib/fathead/cppreference_doc/cppreference-doc/ddg_parse_html.py, lib/fathead/cppreference_doc/cppreference-doc/index2ddg.py, lib/fathead/cppreference_doc/cppreference-doc/index_transform.py, lib/fathead/cppreference_doc/cppreference-doc/link_map.py, lib/fathead/cppreference_doc/cppreference-doc/version.txt, lib/fathead/cppreference_doc/cppreference-doc/xml_utils.py, lib/fathead/cppreference_doc/fetch.sh, lib/fathead/cppreference_doc/parse.sh
The strange and inconvenient setup of cppreference_doc fathead parsing plugins has been discussed several times: https://github.com/duckduckgo/zeroclickinfo-fathead/issues/781, https://github.com/duckduckgo/zeroclickinfo-fathead/pull/539. To recap, the current setup is this:
- create a mirror of cppreference.com using the scripts within cppreference-doc repository
- upload the resulting archive to cppreference.com
- download the archive from cppreference.com (fetch.sh)
- run the parsing scripts within the downloaded archive (parse.sh)
The first two tasks are performed by the cppreference.com maintainers, the last two - by DDG staff or contributors. As a result of this process, any change is inconvenient to develop, as the developer needs to work with both repositories.
Previously I have …
=> cppreference_doc: Commit parsing scripts to this repository
